### ISSUE TITLE
Insert Locality, Building and Shelf

### ISSUE THREAD

**Issue by lbaltaru** [cross-logis/netbuilder#1]
New project (name: username_netbuilder) inside a new empty template.
Alex will add the empty template to the repository.
Each user will create its own branch.

Using Netbuilder to insert:

- one Locality (any coordinates)
- one Building inside Locality
- one Shelf inside the Building

Basic attributes - free choice.

Inspiration resources: 

- existing tests in demo version ?!
- GC project (\\ronas\share\CROSS\CROSS Curs Laurentiu\GC\)

How to run Netbuilder - ToBe documented (maybe like an upgrade).

**Comment by alexctinpirtea** [comment]
@alexctinpirtea 

Use changes made in #4 to update the test classes with actual functionality code.

**Comment by lbaltaru** [comment]
Use WGS84 coordinates:

Max_lat | 479647
-- | --
Min_lng | 4914233

Min_lat | 377977
-- | --
Max_lng | 4959590

**Comment by alexctinpirtea** [comment]
Current example of NetBuilder works as expected, it imports demo data/objects to an existing database. 
See changes in commit 1f1c2076d1857e8f05810d47d4d3a00098e96f20. 

To run this example do the following steps:

- edit your override.properties configuration by changing/adding these settings:

```properties
# Tell NetBuilder not to create/initialize the database schema
cross.db.schemaCreateUpdate=false

# Set this flag to false in order to skip loading configuration 
cross.module.netbuilder.loadConfiguration=false
cross.module.netbuilder.runProjectCustomImport=true
cross.module.reenetbuilder.demoDataSize=1

cross.module.netbuilder.rebuildLinkHierarchy=true
cross.module.netbuilder.rebuildNodeHierarchy=true
cross.module.netbuilder.rebuildExternalIds=true
cross.module.netbuilder.rebuildFulltextIndex=true
```

- run Main class from the example
- run web application to see imported objects
