### ISSUE TITLE
Configure Netuilder to run an import from code

### ISSUE THREAD

**Issue by lbaltaru** [cross-logis/netbuilder#4]
Create necessary java classes (inspired by test_netbuilder_example_01) that will generate data into CROSS from java code and will be run by ree_netbuilder project.

**Comment by alexctinpirtea** [comment]
@alexctinpirtea 

Make a first commit with only the changes related to new classes, not to actual code that updates the database:
- Main.java (updated to call for example TestNetbuilderAlex)
- Netbuilder example class (TestNetbuilderAlex)
- Netbuilder example implemenation class (TestImporterAlex)
- all required methods empty (only with what TODO)

Explanation of Netbuilder property list.
