### ISSUE TITLE
Configure ree_web to run on Tomcat

### ISSUE THREAD

**Issue by lbaltaru** [cross-logis/netbuilder#5]
To be detailed ...

**Comment by alexctinpirtea** [comment]
Web application **ree_web** is now running on Tomcat without any errors on version 2.3.
See commit ed7b5768dee70afe8a26ce22841c458e12f70dc1 to see the changes from the previous 2.2 version.
Further details regarding these changes from version 2.2 to 2.3 will be documented in a wiki page.
